// Regenerates the hosted copies of Circa's legal text.
//
//   dart run tool/export_legal.dart
//
// Play's store listing needs a publicly reachable privacy policy URL, and the
// app needs the same text offline. Rather than maintain two copies and watch
// them drift, `lib/features/legal/legal_content.dart` is the single source and
// this script renders it to Markdown under `docs/legal/`.
//
// Run it whenever that file changes, and commit the result.

import 'dart:io';

import 'package:circa/features/legal/legal_content.dart';

String _render(LegalDocument doc) {
  final b = StringBuffer()
    ..writeln('# Circa — ${doc.title}')
    ..writeln()
    ..writeln('*Effective $kLegalEffectiveDate*')
    ..writeln()
    ..writeln('> ${doc.summary}')
    ..writeln()
    ..writeln('<!-- Generated by tool/export_legal.dart — do not edit by')
    ..writeln('     hand. Edit lib/features/legal/legal_content.dart and')
    ..writeln('     re-run `dart run tool/export_legal.dart`. -->')
    ..writeln();

  for (final section in doc.sections) {
    b
      ..writeln('## ${section.heading}')
      ..writeln();
    for (final paragraph in section.body) {
      b
        ..writeln('- $paragraph')
        ..writeln();
    }
  }
  return b.toString();
}

void main() {
  final dir = Directory('docs/legal')..createSync(recursive: true);

  final outputs = {
    'privacy.md': CircaLegal.privacy,
    'terms.md': CircaLegal.terms,
  };

  for (final entry in outputs.entries) {
    final file = File('${dir.path}/${entry.key}')
      ..writeAsStringSync(_render(entry.value));
    stdout.writeln('wrote ${file.path}');
  }

  if (kCircaContactEmail.contains('example.com')) {
    stderr.writeln(
      '\nWARNING: kCircaContactEmail is still the placeholder. Set a real '
      'address in lib/features/legal/legal_content.dart before uploading to '
      'Play — a policy with no reachable contact is a review rejection.',
    );
    exitCode = 1;
  }
}
